const colors = require("tailwindcss/colors");

module.exports = {
    important: true,
    purge: ["./resources/js/**/*.js", "./resources/js/**/*.jsx"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {
            fontFamily: {
                'roboto': ['Roboto']
              },
              container: {
                center: true
              },
              maxWidth: {
                '1/4': '25%',
                '1/2': '50%',
                '3/4': '75%'
              },
              screens: {
                'sm': '640px',
                'md': '768px',
                'lg': '1024px',
                'xl': '1280px',
                'xxl': '1600px'
             },
            // backgroundImage: theme => ({
            //     'hero-lg': "url('/Images/Utils/bg.jpg`')",
            //     'hero-sm': "url('/Images/Utils/bg.jpg`')",
            //    }),
            colors: {
                theme: {
                    1: "#1C3FAA",
                    2: "#F1F5F8",
                    3: "#2e51bb",
                    4: "#3151BC",
                    5: "#dee7ef",
                    6: "#D32929",
                    7: "#365A74",
                    8: "#D2DFEA",
                    9: "#91C714",
                    10: "#3160D8",
                    11: "#F78B00",
                    12: "#FBC500",
                    13: "#7F9EB9",
                    14: "#E6F3FF",
                    15: "#8DA9BE",
                    16: "#607F96",
                    17: "#FFEFD9",
                    18: "#D8F8BC",
                    19: "#E6F3FF",
                    20: "#2449AF",
                    21: "#284EB2",
                    22: "#395EC1",
                    23: "#D6E1FF",
                    24: "#2e51bb",
                    25: "#C6D4FD",
                    26: "#E8EEFF",
                    27: "#98AFF5",
                    28: "#1A389F",
                    29: "#142C91",
                    30: "#8da3e6",
                    31: "#ffd8d8",
                    32: "#3b5998",
                    33: "#4ab3f4",
                    34: "#517fa4",
                    35: "#0077b5",
                    36: "#d18d96",
                    37: "#c7d2ff",
                    38: "#15329A",
                    40: "#203FAD",
                    41: "#BBC8FD",
                },
                //   custompink: {
                //   '100': '#FFE4F8',
                //   '200': '#DB98B5',
                //   '300': '#EF7AD6',
                //   '400': '#C755B1',
                //   '500': '#D3468F',
                //   '600': '#B42574',
                //   '700': '#96005B',
                //   '800': '#780042',
                //   '900': '#5A002B',
                // },
                custom: {
                    50: "#EAF7FC",
                    100: "#D2EDF6",
                    200: "#BAE4EF",
                    300: "#ACE0EE",
                    400: "#95DAF5",
                    500: "#5FBEEB",
                    600: "#3766B1",
                    700: "#28499E",
                    800: "#223E7E",
                    900: "#072268",
                },
            },
        },
        colors: {
            yellow: colors.yellow,
            gray: colors.coolGray,
            orange: colors.orange,
            blue: colors.blue,
            emerald: colors.emerald,
            red: colors.red,
            green: colors.green,
            cyan: colors.cyan,
            pink: colors.pink,
            indigo: colors.indigo,
            lightBlue: colors.lightBlue,
            teal: colors.teal,
            rose: colors.rose,
            amber: colors.amber,
            lime: colors.lime,
            black: colors.black,
            white: colors.white,
            purple: colors.purple,
            // custom: colors.lightBlue
        },
    },
    variants: {
        zIndex: ["responsive", "hover", "active"],
        position: ["responsive", "hover"],
        padding: ["responsive", "last", "hover", "focus"],
        margin: ["responsive", "last"],
        borderWidth: ["responsive", "last"],
        textColor: ["responsive", "hover", "focus", "group-hover"],
        // animation: ['responsive', 'motion-safe', 'motion-reduce'],
        backgroundColor: [
            "responsive",
            "hover",
            "focus",
            "checked",
            "group-focus",
            "odd",
            "even",
        ],
        shadow: ["responsive", "hover", "focus", "group-hover"],
        borderColor: ["active", "hover", "focus", "odd", "even"],
        fontWeight: ["hover", "focus"],
        ringWidth: ["hover", "active"],
        ringColor: ["hover", "active"],
        backgroundClip: ["hover", "focus"],
        translate: ["active", "group-hover", "hover"],
        animation: ["hover", "focus"],

        extend: {},
    },
    plugins: [],
};
